apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: demo
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
     app: hello-world
  ports:
    - protocol: "TCP"
      port: 5000
      nodePort: 30000